-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.category
(
    categoryid bigint NOT NULL,
    createdat timestamp without time zone NOT NULL,
    name character varying(255),
    needtocook boolean,
    updatedat timestamp without time zone NOT NULL,
    PRIMARY KEY (categoryid)
);

CREATE TABLE public.employee
(
    userid character varying(255) NOT NULL,
    createdat timestamp without time zone NOT NULL,
    expopushtoken character varying(255),
    updatedat timestamp without time zone NOT NULL,
    username character varying(255),
    PRIMARY KEY (userid)
);

CREATE TABLE public.orderitem
(
    orderid character varying(255) NOT NULL,
    orderitemid integer NOT NULL,
    quantity integer,
    productid character varying(255),
    PRIMARY KEY (orderid, orderitemid)
);

CREATE TABLE public.orders
(
    orderid character varying(255) NOT NULL,
    createdat timestamp without time zone NOT NULL,
    orderstatus character varying(255),
    updatedat timestamp without time zone NOT NULL,
    userid character varying(255),
    tableid bigint,
    PRIMARY KEY (orderid)
);

CREATE TABLE public.product
(
    productid character varying(255) NOT NULL,
    createdat timestamp without time zone NOT NULL,
    imagefile character varying(255),
    name character varying(255),
    price double precision,
    updatedat timestamp without time zone NOT NULL,
    categoryid bigint,
    PRIMARY KEY (productid)
);

CREATE TABLE public.serv_table
(
    tableid bigint NOT NULL,
    createdat timestamp without time zone NOT NULL,
    istakeout boolean NOT NULL,
    name character varying(255),
    occupied boolean,
    seats integer,
    updatedat timestamp without time zone NOT NULL,
    PRIMARY KEY (tableid)
);

CREATE TABLE public.usertoken
(
    userid character varying(255) NOT NULL,
    createdat timestamp without time zone NOT NULL,
    token character varying(255) NOT NULL,
    updatedat timestamp without time zone NOT NULL,
    PRIMARY KEY (userid)
);

ALTER TABLE public.orderitem
    ADD FOREIGN KEY (productid)
    REFERENCES public.product (productid)
    NOT VALID;


ALTER TABLE public.orderitem
    ADD FOREIGN KEY (orderid)
    REFERENCES public.orders (orderid)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (userid)
    REFERENCES public.employee (userid)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (tableid)
    REFERENCES public.serv_table (tableid)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (categoryid)
    REFERENCES public.category (categoryid)
    NOT VALID;

END;